services:
  database:
    image: postgres:16.3-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    restart: unless-stopped
    volumes:
      - kuzet:/var/lib/postgresql/data

volumes:
  kuzet: ~
